---
  letsencrypt_src_directory: /usr/local/share/letsencrypt
  letsencrypt_venv: "{{ letsencrypt_src_directory }}/env"
  letsencrypt_cert_domains:
    - "example.com"
  letsencrypt_webroot_path: /var/www/html
  letsencrypt_authenticator: webroot
  letsencrypt_email: "webmaster@example.com"
  letsencrypt_command: "{{ letsencrypt_venv }}/bin/letsencrypt --agree-tos  {% if letsencrypt_rsa_key_size is defined %}--rsa-key-size {{ letsencrypt_rsa_key_size }}{% endif %} --text {% for domain in letsencrypt_cert_domains %}-d {{ domain }} {% endfor %}--email {{ letsencrypt_email }} {% if letsencrypt_server is defined %}--server {{ letsencrypt_server }}{% endif %} --expand"
  letsencrypt_renewal_frequency:
    day: "*"
    hour: 0
    minute: 0
  letsencrypt_renewal_command_args: '--renew-hook "/usr/sbin/service nginx restart"'
