---

- name: install iptables-persistent
  apt:
    name: 'iptables-persistent'
    state: present

- name: set up iptables rules
  copy:
    src: 'iptables.rules.v4'
    dest: '/etc/iptables/rules.v4'
  notify: restart iptables

- name: set up ip6tables rules
  copy:
    src: 'iptables.rules.v6'
    dest: '/etc/iptables/rules.v6'
  notify: restart iptables
