---
- name: create bot user
  user:
    name: '{{ bot.user }}'
    system: yes

- name: create bot dir
  file:
    path: '{{ bot.basedir }}'
    state: directory
    owner: '{{ bot.user }}'

- name: copy bot files
  copy:
    src: '../{{ item }}'
    dest: '{{ bot.basedir }}/{{ item }}'
    owner: '{{ bot.user }}'
  notify: restart bot
  with_items:
    - 'calbot.py'
    - 'requirements.txt'
    - 'COPYING'
    - 'calbot/'

- name: install dependencies
  pip:
    executable: /usr/bin/pip3
    requirements: '{{ bot.basedir }}/requirements.txt'
  notify: restart bot

- name: create config
  template:
    src: bot.cfg
    dest: '{{ bot.basedir }}/{{ bot.service_name }}.cfg'
  notify: restart bot

- name: install systemd service
  template:
    src: bot.service
    dest: '/etc/systemd/system/{{ bot.service_name }}.service'
  notify: update systemd
