---
- name: Install Python, Nginx, Letsencypt
  hosts: bothosts
  remote_user: root

  roles:
    - common
    - locales
    - python
    - nginx
    - letsencrypt
    - nginx-bot
    - bot-provision
