---

- name: copy bot files
  copy:
    src: '../{{ item }}'
    dest: '{{ bot_basedir }}/{{ item }}'
    owner: '{{ bot_user }}'
    group: '{{ bot_user }}'
  notify: restart bot
  with_items:
    - 'calbot.py'
    - 'requirements.txt'
    - 'COPYING'

- name: copy bot files
  synchronize:
    src: '../calbot/'
    dest: '{{ bot_basedir }}/calbot/'
    rsync_opts:
      - '--chown={{ bot_user }}:{{ bot_user }}'
  notify: restart bot

- name: install dependencies
  pip:
    virtualenv: '{{ bot_basedir }}/venv'
    virtualenv_python: '{{ bot_python }}'
    requirements: '{{ bot_basedir }}/requirements.txt'
  notify: restart bot

- name: create config
  template:
    src: bot.cfg
    dest: '{{ bot_basedir }}/{{ bot_service_name }}.cfg'
  notify: restart bot

- name: start service
  service:
    name: '{{ bot_service_name }}'
    state: started
